<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewEmergencyLightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Data LOT A
            ['map_no' => 'A.1', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.2', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.3', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.4', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.5', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.6', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.7', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.8', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.9', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.10', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.11', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.12', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.13', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.14', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.15', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.16', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.17', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.18', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.18', 'location' => 'B1 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'A.19', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.20', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.21', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.22', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.23', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.24', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.25', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.26', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.27', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.28', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.29', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.30', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.31', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.32', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.33', 'location' => 'B1 LOT 2', 'type_light' => 'TL LED'],
            ['map_no' => 'A.34', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.35', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.36', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.37', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.38', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.39', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.40', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.41', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.42', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.43', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.44', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.45', 'location' => 'B1 LOT 3', 'type_light' => 'TL LED'],
            ['map_no' => 'A.46', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.47', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.48', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.49', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.50', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.51', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.52', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.53', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.54', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.55', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.56', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.57', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.58', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.59', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.60', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.61', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.62', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.63', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.64', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.65', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.66', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.67', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.68', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.69', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.70', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.71', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.72', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.73', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.74', 'location' => 'B1 LOT 4', 'type_light' => 'TL LED'],
            ['map_no' => 'A.75', 'location' => 'B1 LOT 5', 'type_light' => 'TL LED'],
            ['map_no' => 'A.76', 'location' => 'B1 LOT 5', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'A.77', 'location' => 'B1 LOT 5', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'A.78', 'location' => 'B1 LOT 5', 'type_light' => 'TL LED'],
            ['map_no' => 'A.79', 'location' => 'B1 LOT 5', 'type_light' => 'TL LED'],
            ['map_no' => 'A.80', 'location' => 'B1 LOT 5', 'type_light' => 'TL LED'],
            // ... Tambahkan data lainnya untuk LOT A berdasarkan gambar Anda

            // Data LOT B
            ['map_no' => 'B.1', 'location' => 'B2a LOT 17', 'type_light' => 'TL LED'],
            ['map_no' => 'B.2', 'location' => 'B2a LOT 17', 'type_light' => 'TL LED'],
            ['map_no' => 'B.3', 'location' => 'B2a LOT 17', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.4', 'location' => 'B2a LOT 17', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.5', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.6', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.7', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.8', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.9', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.10', 'location' => 'B2a LOT 16', 'type_light' => 'TL LED'],
            ['map_no' => 'B.11', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.12', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.13', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.14', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.15', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.16', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.17', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.18', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.19', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.20', 'location' => 'B2a LOT 15', 'type_light' => 'TL LED'],
            ['map_no' => 'B.21', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.22', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.23', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.24', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.25', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.26', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.27', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.28', 'location' => 'B2a LOT 14', 'type_light' => 'TL LED'],
            ['map_no' => 'B.29', 'location' => 'B2a LOT 13', 'type_light' => 'TL LED'],
            ['map_no' => 'B.30', 'location' => 'B2a LOT 13', 'type_light' => 'TL LED'],
            ['map_no' => 'B.31', 'location' => 'B2a LOT 13', 'type_light' => 'TL LED'],
            ['map_no' => 'B.32', 'location' => 'B2a LOT 13', 'type_light' => 'TL LED'],
            ['map_no' => 'B.33', 'location' => 'B2a LOT 13', 'type_light' => 'TL LED'],
            ['map_no' => 'B.34', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.35', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.36', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.37', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.38', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.39', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.40', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.41', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.42', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.43', 'location' => 'B2a LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'B.44', 'location' => 'B2a LOT 12', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.45', 'location' => 'B2a LOT 12', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.46', 'location' => 'B2a LOT 1', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.47', 'location' => 'B2a LOT 1', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.48', 'location' => 'B2a LOT 2', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.49', 'location' => 'B2a LOT 2', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.50', 'location' => 'B2a LOT 3', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'B.51', 'location' => 'B2a LOT 3', 'type_light' => 'HIGH BAY LED'],
            // ... Tambahkan data lainnya untuk LOT B berdasarkan gambar Anda

            // Data LOT C
            ['map_no' => 'C.1', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.2', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.3', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.4', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.5', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.6', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.7', 'location' => 'B2 LOT 24', 'type_light' => 'TL LED'],
            ['map_no' => 'C.8', 'location' => 'B2 LOT 24', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.9', 'location' => 'B2 LOT 24', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.10', 'location' => 'B2 LOT 23', 'type_light' => 'TL LED'],
            ['map_no' => 'C.11', 'location' => 'B2 LOT 23', 'type_light' => 'TL LED'],
            ['map_no' => 'C.12', 'location' => 'B2 LOT 23', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.13', 'location' => 'B2 LOT 23', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.14', 'location' => 'B2 LOT 23', 'type_light' => 'TL LED'],
            ['map_no' => 'C.15', 'location' => 'B2 LOT 23', 'type_light' => 'TL LED'],
            ['map_no' => 'C.16', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.17', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.18', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.19', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.20', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.21', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.22', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.23', 'location' => 'B2 LOT 22', 'type_light' => 'TL LED'],
            ['map_no' => 'C.24', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.25', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.26', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.27', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.28', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.29', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.30', 'location' => 'B2 LOT 21', 'type_light' => 'TL LED'],
            ['map_no' => 'C.31', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.32', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.33', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.34', 'location' => 'B2 LOT 20', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.35', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.36', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.37', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.39', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.40', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.41', 'location' => 'B2 LOT 20', 'type_light' => 'TL LED'],
            ['map_no' => 'C.42', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.43', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.44', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.45', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.46', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.47', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.48', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.49', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.50', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.51', 'location' => 'B2 LOT 12', 'type_light' => 'TL LED'],
            ['map_no' => 'C.73', 'location' => 'B2 LOT 10', 'type_light' => 'TL LED'],
            ['map_no' => 'C.74', 'location' => 'B2 LOT 10', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'C.75', 'location' => 'B2 LOT 10', 'type_light' => 'HIGH BAY LED'],

            // Data LOT D
            ['map_no' => 'D.1', 'location' => 'C2 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'D.2', 'location' => 'C2 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'D.3', 'location' => 'C2 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'D.4', 'location' => 'C2 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'D.5', 'location' => 'C2 LOT 1', 'type_light' => 'TL LED'],
            ['map_no' => 'D.6', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'D.7', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'D.8', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'D.9', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'D.10', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            ['map_no' => 'D.11', 'location' => 'C2 LOT 6', 'type_light' => 'HIGH BAY LED'],
            
            // ... Tambahkan data lainnya untuk LOT C berdasarkan gambar Anda
        ];

        DB::table('new_emergency_lights')->insert($data); // Pastikan tabel 'lighting_table' sesuai dengan tabel di database Anda
    }
}
